apiVersion: v1
kind: Pod
metadata:
  name: dual-container-pod
spec:
  containers:
  - name: container1
    image: alpine:3.12.0
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - mountPath: /etc/a
      name: shared-volume
  - name: container2
    image: alpine:3.12.0
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - mountPath: /etc/b
      name: shared-volume
  volumes:
  - name: shared-volume
    emptyDir: {}